name: Deploy SiPelDes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/sipledes
            git pull origin main
            docker build -t sipledes .
            docker stop sipledes || true
            docker rm sipledes || true
            docker run -d \
              --name sipledes \
              --env-file .env \
              --network host \
              -e AWS_DEFAULT_REGION=ap-southeast-1 \
              --restart always \
              sipledes
